sudo: required
services:
  - docker
branches:
  only: 
    - master       
script:
  - echo "skipping tests"  
after_success: 
  - docker-compose up --build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push katbert/chat-app_nginx_1
  - docker push katbert/chat-app_nodejs_1