sudo: required
services:
  - docker
branches:
  only: 
    - master       
script:
  - echo "skipping tests"  
after_success: 
  - docker-compose build 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chatapp_nginx:latest
  - docker push chatapp_nodejs:latest