sudo: required
services:
  - docker
branches:
  only: 
    - master       
script:
  - echo "skipping tests"  
after_success: 
  - docker-compose build 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push katbert/chat-client
  - docker push katbert/chat-server
deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: bugleev-chat
  env: fmlife-env
  bucket_name: elasticbeanstalk-eu-north-1-263451985759
  bucket_path: buybots-chat
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY  