version: "3.1"
services:
  
  nginx:
    build: 
      context: ./client
    restart: always 
    ports:
      - "8000:80"     
    depends_on:      
      - nodejs
  nodejs:
    build: 
      context: ./server
    environment: 
      NODE_ENV: production   
    restart: always   
 
    
