version: "3.1"
services:
  
  nginx:
    image: katbert/chat-client
    build: 
      context: ./client
    restart: always 
    ports:
      - "8000:80"     
    depends_on:      
      - nodejs
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets-encrypt
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
  nodejs:
    image: katbert/chat-server
    build: 
      context: ./server
    environment: 
      NODE_ENV: production
      PORT: 5555    
      CLEAN_UPLOADS_DAYS: 10
      UPLOADS_DIR: uploads   
    restart: always   
volumes:
  certs:
 
   
    
