version: "3.1"
services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:    
      - ./server/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/conf/gzip.conf:/etc/nginx/conf.d/gzip.conf     
    depends_on:      
      - nodejs
  nodejs:
    build: .
    environment: 
      NODE_ENV: production   
    restart: always   
    command: ["yarn", "server"]
    
