version: "3.1"
services:
  
  nginx:
    image: katbert/chat-client
    build: 
      context: ./client
    restart: always 
    ports:
      - "8000:80"     
      - "443:443"     
    depends_on:      
      - nodejs
  nodejs:
    image: katbert/chat-server
    build: 
      context: ./server
    environment: 
      NODE_ENV: production
      PORT: 5555    
      CLEAN_UPLOADS_DAYS: 10
      UPLOADS_DIR: uploads   
    restart: always   
 
    
